/**
 * Tanıtım sayfası metinleri (TR/EN).
 *
 * Genel sözlük (`i18n/dict.ts`) ana pakete girer; bu metinler yalnız tanıtım
 * sayfasının tembel yüklenen parçasında durur. İngilizce nesne Türkçe'nin
 * tipini taşır — bir alan eksikse derlenmez.
 */
const tr = {
  nav: {
    features: "Özellikler",
    lifecycle: "Yaşam döngüsü",
    network: "Ağ",
    engineering: "Mühendislik",
    login: "Sisteme giriş",
  },
  hero: {
    // Büyük harfle yazılı: CSS büyütmesi Türkçe sayfada "SUİTE" üretirdi.
    eyebrow: "TROYA SUITE · ELEKTRONİK BİLETLEME",
    title1: "Komut satırından",
    title2: "tek tıka.",
    sub: "Bilet ve EMD kesiminden kupon yaşam döngüsüne, iadeden check-in'e kadar bir PSS'in biletleme çekirdeği — IATA kurallarıyla, tek bir modern arayüzde.",
    primary: "Sisteme giriş",
    secondary: "Neler yapabildiğini gör",
    stats: [
      { value: "17", label: "kupon statüsü" },
      { value: "15", label: "Handbook bölümü" },
      { value: "5", label: "yetki rolü" },
      { value: "2", label: "dil · TR / EN" },
    ],
    scroll: "Kaydır",
  },
  statement: "Bir biletin tüm hayatı. Kesildiği andan uçulduğu ana, iadesinden denetimine kadar — her adım değişmez bir kayıt olarak saklanır ve tek ekranda okunur.",
  lifecycle: {
    eyebrow: "Kupon yaşam döngüsü",
    title: "Her kuponun bir hikâyesi var.",
    sub: "Statüler açık bir durum makinesiyle ilerler. İzin verilmeyen geçiş yapılamaz, son statüler kapanır; her geçiş zaman çizgisine düşer.",
    steps: [
      { code: "O", name: "Açık", text: "Bilet kesilir. Kupon kullanıma açıktır; exchange, iade ve void bu andan itibaren kurallarıyla mümkündür." },
      { code: "C", name: "Check-in", text: "Yolcu kontuarda kabul edilir. Koltuk uçak tipine göre, uygunluk kurallarıyla atanır." },
      { code: "L", name: "Uçağa bindi", text: "Biniş kartı okutulur. Kupon kapıda kaldırılır; binmeyen yolcu no-show olarak kalır." },
      { code: "F", name: "Uçuldu", text: "Uçuş kapanır, kupon son statüsüne ulaşır ve settlement için kayda geçer." },
    ],
    gridTitle: "Handbook'un 17 statüsü, tek sözlük.",
    gridSub: "Renk aileyi, kod kimliği anlatır.",
    ticket: "Elektronik bilet",
    passenger: "Yolcu",
    flight: "Sefer",
    status: "Statü",
    timeline: "Zaman çizgisi",
    events: ["Bilet kesildi", "Check-in yapıldı", "Uçağa bindi", "Uçuş kapandı"],
  },
  bento: {
    eyebrow: "Özellikler",
    title: "Tek platform. Her masa için.",
    sub: "Satıştan kontuara, operasyondan muhasebeye — aynı motor, aynı kurallar.",
    issue: { title: "Bilet kesim", text: "Uçuş ve ücret elle yazılmaz. Sistem listeler, personel seçer; RBD ve ücret kodu kendiliğinden oluşur.", chips: ["En düşük", "Ortalama", "En yüksek"] },
    money: { title: "Exchange · İade · Void", text: "Ceza, vergi iadesi ve KDV'yi sistem hesaplar. Personel tutar yazmaz, sonucu doğrular.", lines: ["Ücret", "İptal cezası", "İade edilen vergi", "Yolcuya iade"] },
    seat: { title: "QuickCheck-in", text: "Uçak tipine göre koltuk haritası. Çıkış sırası, bebekli ve özel yolcu kuralları sunucuda da zorlanır." },
    hub: { title: "HUB Kontrol", text: "Canlı kalkış panosu, önem sırasına dizilmiş uyarılar ve rötar tazminatı tek ekranda.", cols: ["Sefer", "Varış", "Kapı", "Durum"], states: ["Biniş", "Son çağrı", "Zamanında", "Rötarlı"] },
    reports: { title: "Raporlar", text: "Satış, mali rapor, KDV kırılımı ve imzalı dönem kapanış belgesi." },
    palette: { title: "⌘K", text: "Bilet, PNR, EMD ya da order — bir tuş, bir numara.", query: "235 1234567890", results: ["Bilet · ERDOGAN/AHMET", "EMD · Fazla bagaj", "PNR · XQ7T2M"] },
    res: { title: "QuickRes", text: "PNR, uygunluk ve bilet süresi. Rezervasyondan tek tıkla bilete." },
    rights: { title: "Yolcu hakları", text: "EU261, SHY-YOLCU ve UK261'e göre tazminat hesabı." },
    roles: { title: "5 rol, net yetki", text: "Personelden yöneticiye kümülatif yetki. Kilitli buton nedenini söyler.", names: ["Personel", "Süpervizör", "Şef", "Müdür", "Admin"] },
    chat: { title: "Ekip mesajlaşması", text: "Canlı sohbet, kanallar ve bilete iliştirilen mesajlar.", msg1: "TK1591 için waiver onaylandı mı?", msg2: "Onaylandı, bileti iliştirdim." },
    docs: { title: "EMD · PTA · ADM/ACM", text: "Hizmet belgeleri, önceden ödenmiş biletler ve acente dekontları." },
    lang: { title: "Türkçe ve İngilizce", text: "Arayüz, hata mesajları ve belgeler iki dilde." },
  },
  showcase: {
    eyebrow: "Arayüz",
    title: "Kriptik ekranın yerine berraklık.",
    sub: "Troya terminalinde ezberlenen komutlar burada birer tıklama. Aynı komut, iki yüzey: terminal de arayüz de aynı motora gider.",
    terminal: "Eskiden",
    ui: "Şimdi",
    commands: ["TKTT/2351234567890", "TRF/CPN1/INV", "TWD/SCHD", "ETKT/VOID/235…"],
    window: {
      search: "Bilet, PNR, yolcu ara…",
      actions: ["Exchange", "Refund", "Void"],
      coupons: "Kuponlar",
      total: "Toplam",
      open: "Açık",
      flown: "Uçuldu",
    },
  },
  network: {
    eyebrow: "INTERLINE",
    title: "Tek kontrol. Bütün ağ.",
    sub: "Kupon kontrolünü aynı anda tek taşıyıcı tutar. Devir yalnız bilateral anlaşmayla yapılır; her statü değişikliği partnerlere bildirilir.",
    points: [
      { title: "Kontrol devri", text: "Validating carrier'dan partnere, süreli ve geri alınabilir." },
      { title: "ETSU", text: "Statü değişiklikleri partner veritabanlarına yayınlanır." },
      { title: "EDIFACT · NDC", text: "Interline mesajları tek gelen kutusunda." },
    ],
    hub: "İstanbul",
  },
  engineering: {
    eyebrow: "Mühendislik",
    title: "Kayıt, domainin kendisidir.",
    sub: "Durum olaylardan türetilir; hiçbir şey üzerine yazılmaz. Bu yüzden her iade, her void, her kontrol devri sonradan okunabilir.",
    pillars: [
      { title: "Event sourcing", text: "Her değişiklik değişmez bir olay. Denetim kaydı ayrı bir özellik değil, sistemin ta kendisi." },
      { title: "CQRS", text: "Yazma ve okuma ayrı. Arama ve raporlar okuma modelinden, komutlar olaylardan." },
      { title: "Durum makinesi", text: "17 statü, açık geçişler. İzin verilmeyen geçiş reddedilir." },
      { title: "Idempotency", text: "Çift tıklama çift satış üretmez. Aynı işlem, aynı sonuç." },
      { title: "Outbox", text: "Kayıt ve mesaj yayını aynı işlemde. Olay kaybolmaz." },
      { title: "Hexagonal", text: "Domain çerçeve bilmez. Fiyatlama, DCS ve envanter port arkasında." },
    ],
    events: ["TicketIssued", "CouponCheckedIn", "CouponLifted", "CouponFlown", "CouponsRefunded", "ControlGranted"],
    store: "Olay deposu · yalnız ekleme",
  },
  iata: {
    title: "IATA kurallarıyla konuşur.",
    items: [
      "Ch 1 · Elektronik bilet", "Ch 2 · Bilet girdileri", "Ch 5 · EMD", "Ch 9 · PTA", "Ch 10 · UATP",
      "Ch 12 · Reissue", "Ch 13 · IRROP · FIM", "Ch 14 · Vergi", "Ch 15 · İade", "Res. 850m · ADM",
      "Res. 1700 · SSR", "RP 1726 · CO₂", "EU261", "SHY-YOLCU", "UK261",
    ],
  },
  cta: {
    title: "Siz hazırsanız, sistem hazır.",
    sub: "Beş rol, üç modül, tek motor. Giriş yapın ve bir bileti baştan sona yönetin.",
    primary: "Sisteme giriş",
    secondary: "Dokümantasyon",
  },
  footer: {
    line: "Troya Suite — IATA Ticketing Handbook temelli biletleme platformu.",
    note: "Bu bir tanıtım prototipidir; veriler örnektir.",
  },
};

export type LandingCopy = typeof tr;

const en: LandingCopy = {
  nav: {
    features: "Features",
    lifecycle: "Lifecycle",
    network: "Network",
    engineering: "Engineering",
    login: "Sign in",
  },
  hero: {
    eyebrow: "Troya Suite · Electronic ticketing",
    title1: "From command line",
    title2: "to one click.",
    sub: "From ticket and EMD issuance to the coupon lifecycle, from refunds to check-in — the ticketing core of a PSS, built on IATA rules, in one modern interface.",
    primary: "Sign in",
    secondary: "See what it can do",
    stats: [
      { value: "17", label: "coupon statuses" },
      { value: "15", label: "Handbook chapters" },
      { value: "5", label: "access roles" },
      { value: "2", label: "languages · TR / EN" },
    ],
    scroll: "Scroll",
  },
  statement: "The whole life of a ticket. From the moment it is issued to the moment it is flown, from refund to audit — every step is kept as an immutable record and read on a single screen.",
  lifecycle: {
    eyebrow: "Coupon lifecycle",
    title: "Every coupon has a story.",
    sub: "Statuses move through an explicit state machine. A disallowed transition cannot happen, final statuses close; every transition lands on the timeline.",
    steps: [
      { code: "O", name: "Open", text: "The ticket is issued. The coupon is open for use; exchange, refund and void follow their rules from here on." },
      { code: "C", name: "Checked in", text: "The passenger is accepted at the counter. The seat is assigned by aircraft type, under eligibility rules." },
      { code: "L", name: "Lifted", text: "The boarding pass is scanned and the coupon is lifted at the gate; a passenger who does not board stays a no-show." },
      { code: "F", name: "Flown", text: "The flight closes, the coupon reaches its final status and is recorded for settlement." },
    ],
    gridTitle: "The Handbook's 17 statuses, one vocabulary.",
    gridSub: "Colour tells the family, the code tells the identity.",
    ticket: "Electronic ticket",
    passenger: "Passenger",
    flight: "Flight",
    status: "Status",
    timeline: "Timeline",
    events: ["Ticket issued", "Checked in", "Boarded", "Flight closed"],
  },
  bento: {
    eyebrow: "Features",
    title: "One platform. Every desk.",
    sub: "From sales to the counter, from operations to accounting — the same engine, the same rules.",
    issue: { title: "Ticket issuance", text: "Flights and fares are never typed. The system lists, the agent picks; booking class and fare basis follow.", chips: ["Lowest", "Average", "Highest"] },
    money: { title: "Exchange · Refund · Void", text: "Penalties, tax refunds and VAT are calculated by the system. Agents verify the result instead of typing amounts.", lines: ["Fare", "Cancellation penalty", "Taxes refunded", "Refund to passenger"] },
    seat: { title: "QuickCheck-in", text: "A seat map for each aircraft type. Exit-row, infant and special-passenger rules are enforced on the server too." },
    hub: { title: "HUB Control", text: "A live departures board, alerts ranked by severity and delay compensation on one screen.", cols: ["Flight", "To", "Gate", "Status"], states: ["Boarding", "Final call", "On time", "Delayed"] },
    reports: { title: "Reports", text: "Sales, financial report, VAT breakdown and a signed period-closing document." },
    palette: { title: "⌘K", text: "Ticket, PNR, EMD or order — one key, one number.", query: "235 1234567890", results: ["Ticket · ERDOGAN/AHMET", "EMD · Excess baggage", "PNR · XQ7T2M"] },
    res: { title: "QuickRes", text: "PNR, availability and ticketing time limit. From booking to ticket in one click." },
    rights: { title: "Passenger rights", text: "Compensation under EU261, SHY-YOLCU and UK261." },
    roles: { title: "5 roles, clear access", text: "Cumulative permissions from agent to admin. A locked button tells you why.", names: ["Agent", "Supervisor", "Chief", "Manager", "Admin"] },
    chat: { title: "Team messaging", text: "Live chat, channels and messages with tickets attached.", msg1: "Was the waiver for TK1591 approved?", msg2: "Approved — ticket attached." },
    docs: { title: "EMD · PTA · ADM/ACM", text: "Service documents, prepaid tickets and agency memos." },
    lang: { title: "Turkish and English", text: "Interface, error messages and documents in both languages." },
  },
  showcase: {
    eyebrow: "Interface",
    title: "Clarity instead of a cryptic screen.",
    sub: "Commands memorised on the Troya terminal are a click here. One command, two surfaces: terminal and interface reach the same engine.",
    terminal: "Before",
    ui: "Now",
    commands: ["TKTT/2351234567890", "TRF/CPN1/INV", "TWD/SCHD", "ETKT/VOID/235…"],
    window: {
      search: "Search ticket, PNR, passenger…",
      actions: ["Exchange", "Refund", "Void"],
      coupons: "Coupons",
      total: "Total",
      open: "Open",
      flown: "Flown",
    },
  },
  network: {
    eyebrow: "Interline",
    title: "One control. The whole network.",
    sub: "Only one carrier holds coupon control at a time. Hand-over needs a bilateral agreement, and every status change is broadcast to partners.",
    points: [
      { title: "Control transfer", text: "From the validating carrier to a partner — time-limited and recallable." },
      { title: "ETSU", text: "Status changes are published to partner databases." },
      { title: "EDIFACT · NDC", text: "Interline messages in a single inbox." },
    ],
    hub: "Istanbul",
  },
  engineering: {
    eyebrow: "Engineering",
    title: "The record is the domain.",
    sub: "State is derived from events; nothing is overwritten. That is why every refund, every void, every control transfer can be read back later.",
    pillars: [
      { title: "Event sourcing", text: "Every change is an immutable event. The audit trail is not a feature — it is the system." },
      { title: "CQRS", text: "Writes and reads are separate. Search and reports read a projection; commands write events." },
      { title: "State machine", text: "17 statuses, explicit transitions. A disallowed transition is refused." },
      { title: "Idempotency", text: "A double click never sells twice. Same operation, same result." },
      { title: "Outbox", text: "The record and the message are written in one transaction. No event is lost." },
      { title: "Hexagonal", text: "The domain knows no framework. Pricing, DCS and inventory sit behind ports." },
    ],
    events: ["TicketIssued", "CouponCheckedIn", "CouponLifted", "CouponFlown", "CouponsRefunded", "ControlGranted"],
    store: "Event store · append only",
  },
  iata: {
    title: "It speaks IATA.",
    items: [
      "Ch 1 · Electronic ticket", "Ch 2 · Ticket entries", "Ch 5 · EMD", "Ch 9 · PTA", "Ch 10 · UATP",
      "Ch 12 · Reissue", "Ch 13 · IRROP · FIM", "Ch 14 · Taxes", "Ch 15 · Refunds", "Res. 850m · ADM",
      "Res. 1700 · SSR", "RP 1726 · CO₂", "EU261", "SHY-YOLCU", "UK261",
    ],
  },
  cta: {
    title: "Ready when you are.",
    sub: "Five roles, three modules, one engine. Sign in and take a ticket from start to finish.",
    primary: "Sign in",
    secondary: "Documentation",
  },
  footer: {
    line: "Troya Suite — a ticketing platform built on the IATA Ticketing Handbook.",
    note: "This is a demonstration prototype; the data is sample data.",
  },
};

export const COPY = { tr, en } as const;
