/**
 * Tanıtım sayfası metinleri (TR/EN).
 *
 * Genel sözlük (`i18n/dict.ts`) ana pakete girer; bu metinler yalnız tanıtım
 * sayfasının tembel yüklenen parçasında durur. İngilizce nesne Türkçe'nin
 * tipini taşır — bir alan eksikse derlenmez.
 */
const tr = {
  nav: {
    product: "Ürün",
    modules: "Modüller",
    lifecycle: "Yaşam döngüsü",
    architecture: "Mimari",
    login: "Sisteme giriş",
  },
  hero: {
    badge: "IATA Ticketing Handbook temelli",
    badgeCta: "Canlı demo",
    title1: "Biletleme,",
    title2: "yeniden tasarlandı.",
    sub: "Troya Suite; bilet ve EMD kesiminden exchange, iade ve check-in'e kadar bir PSS'in biletleme çekirdeğini IATA kurallarıyla tek ve modern bir arayüzde birleştirir.",
    primary: "Sisteme giriş",
    secondary: "Ürünü keşfet",
    trust: ["17 kupon statüsü", "15 Handbook bölümü", "Türkçe · English"],
    hub: "İstanbul · IST",
    ticketCard: { label: "Elektronik bilet", route: "IST → LHR · TK1979" },
    etsuCard: { label: "ETSU · statü yayını", text: "Partnerlere bildirildi", time: "az önce" },
    drag: "Sürükleyerek çevirin",
    live: "canlı",
  },
  product: {
    eyebrow: "Ürün",
    title: "Kriptik ekranın yerine berraklık.",
    sub: "Terminalde ezberlenen komutlar burada birer tıklama. Aynı komut iki yüzeyde çalışır: terminal de arayüz de aynı motora gider.",
    url: "troya-suite / tickets / 2351234567890",
    alt: "Troya Suite bilet kaydı ekranı: elektronik bilet, kuponlar, geçerlilik ve işlemler",
    mapTitle: "Tek komut, iki yüzey",
    map: [
      { cmd: "TKTT/2351234567890", ui: "Bileti aç" },
      { cmd: "TRF/CPN1/INV", ui: "İade" },
      { cmd: "ETKT/VOID/235…", ui: "Void" },
      { cmd: "TWD/SCHD", ui: "Tarife değişikliği" },
    ],
  },
  standards: {
    label: "Sektör standartlarıyla konuşur",
    items: [
      "IATA Ticketing Handbook", "Resolution 850m", "Resolution 1700", "RP 1726", "ATPCO Cat 16 · 31 · 33",
      "EU 261/2004", "SHY-YOLCU", "UK261", "EDIFACT · NDC", "PCI DSS",
    ],
  },
  modules: {
    eyebrow: "Modüller",
    title: "Tek platform. Her masa için.",
    sub: "Satıştan kontuara, operasyondan muhasebeye — aynı motor, aynı kurallar.",
    tabs: [
      {
        key: "issue", label: "Biletleme", img: "fare", focus: 64,
        title: "Ücreti sistem önerir, personel seçer.",
        text: "Güzergâh ve tarih girilir; sistem seferleri ve ücret ailelerini listeler. RBD, ücret kodu ve vergi dökümü kendiliğinden oluşur.",
        bullets: ["Sefer ve ücret listesi", "Kesim öncesi özet ve beyan onayı", "Grup ve aile kesimi, kucak bebeği", "Çift tıklamaya karşı idempotent kesim"],
      },
      {
        key: "servicing", label: "Satış sonrası", img: "ticket", focus: 8,
        title: "Exchange, iade, void — hesabı sistem yapar.",
        text: "Ceza, vergi iadesi ve KDV tarife kurallarından hesaplanır. Personel tutar yazmaz; sonucu ve gerekçesini doğrular.",
        bullets: ["Cat 16 · 31 · 33 ceza katmanı", "Vergi bazında iade edilebilirlik", "Reissue farkı ve bakiye belgesi", "Kontrol devri ve refund-cancel"],
      },
      {
        key: "checkin", label: "Check-in", img: "checkin", focus: 62,
        title: "Uçak tipine göre koltuk, kurala göre kabul.",
        text: "Koltuk haritası gerçek kabin düzeninden çizilir. Çıkış sırası, bebekli ve özel yolcu kuralları sunucuda da zorlanır.",
        bullets: ["Beş uçak tipi, gerçek kabin düzeni", "APIS ve seyahat belgesi kontrolü", "Kabul penceresi, onaylı geç kabul", "Biniş kartı, kupon C → L → F"],
      },
      {
        key: "ops", label: "Operasyon", img: "ops", focus: 20,
        title: "Bütün hub, tek ekranda.",
        text: "Canlı kalkış panosu, önem sırasına dizilmiş uyarılar ve yolcu hakları. Rötar olduğunda tazminat tutarı hazır gelir.",
        bullets: ["A-CDM uçuş durumları", "No-show, MCT ve bagaj uyarıları", "EU261 · SHY-YOLCU · UK261", "Toplu tarife değişikliği"],
      },
      {
        key: "reports", label: "Raporlama", img: "financial", focus: 18,
        title: "Olay kaydından türeyen muhasebe.",
        text: "Satış, mali rapor ve KDV kırılımı olay kaydından hesaplanır. Dönem kapanışı imzalı bir belge üretir ve dönemi kilitler.",
        bullets: ["Ceza, vergi ve KDV kırılımı", "Dönem kapanışı ve kilit", "ADM / ACM dekontları", "Excel uyumlu dışa aktarım"],
      },
    ],
    pause: "Otomatik geçişi durdur",
    play: "Otomatik geçişi başlat",
  },
  lifecycle: {
    eyebrow: "Kupon yaşam döngüsü",
    title: "Her kuponun bir hikâyesi var.",
    sub: "Statüler açık bir durum makinesiyle ilerler. İzin verilmeyen geçiş yapılamaz, son statüler kapanır; her geçiş zaman çizgisine düşer.",
    steps: [
      { code: "O", name: "Açık", text: "Bilet kesilir; kupon kullanıma açıktır." },
      { code: "C", name: "Check-in", text: "Yolcu kabul edilir, koltuk atanır." },
      { code: "L", name: "Uçağa bindi", text: "Biniş kartı kapıda okutulur." },
      { code: "F", name: "Uçuldu", text: "Uçuş kapanır, kupon settlement'a geçer." },
    ],
    gridTitle: "Handbook'un 17 statüsü, tek sözlük.",
    gridSub: "Renk aileyi, kod kimliği anlatır.",
    interim: "Ara statüler",
    final: "Son statüler",
  },
  capabilities: {
    eyebrow: "Yetenekler",
    title: "Günlük işin tamamı, tek yerde.",
    sub: "Handbook'un büyük fonksiyonları kurallarıyla birlikte: her biri kilitli buton, açık gerekçe ve denetim kaydıyla gelir.",
    items: [
      { icon: "ticket", title: "Bilet ve EMD", text: "EMD-A ve EMD-S, bilete bağlı ya da bağımsız; RFISC ile hizmet kodu." },
      { icon: "refund", title: "İade ve void", text: "Satış günü void, tarife kuralıyla iade, aynı dönemde refund-cancel." },
      { icon: "exchange", title: "Exchange ve reissue", text: "Ücret farkı, vergi farkı ve bakiye; geçerlilik kurala göre korunur." },
      { icon: "control", title: "Kontrol devri", text: "Kupon kontrolü tek taşıyıcıda; devir bilateral anlaşmayla ve süreli." },
      { icon: "irrop", title: "IRROP ve FIM", text: "Havayolu kaynaklı değişiklikte ciro ve FIM referansı." },
      { icon: "rights", title: "Yolcu hakları", text: "EU261, SHY-YOLCU ve UK261'e göre tazminat tutarı." },
      { icon: "queue", title: "Kuyruklar", text: "Bilet süresi, IRROP ve tarife değişikliği işleri kayıttan türer." },
      { icon: "memo", title: "ADM / ACM", text: "Res. 850m: itiraz süresi, dokuz ay sınırı, BSP dönemi." },
      { icon: "roles", title: "Beş rol, net yetki", text: "Kümülatif yetki matrisi; kilitli buton nedenini söyler." },
      { icon: "chat", title: "Ekip mesajlaşması", text: "Kanallar, çevrimiçi durumu ve bilete iliştirilen mesajlar." },
      { icon: "palette", title: "⌘K komut paleti", text: "Bilet, EMD, PNR ya da order — bir tuş, bir numara." },
      { icon: "lang", title: "Türkçe ve İngilizce", text: "Arayüz, hata mesajları ve belgeler iki dilde." },
    ],
  },
  stats: [
    { value: "17", label: "resmî kupon statüsü" },
    { value: "15", label: "Handbook bölümü" },
    { value: "37", label: "ekran" },
    { value: "600+", label: "otomatik test" },
  ],
  architecture: {
    eyebrow: "Mimari",
    title: "Kayıt, domainin kendisidir.",
    sub: "Durum olaylardan türetilir; hiçbir şey üzerine yazılmaz. Her iade, her void, her kontrol devri sonradan okunabilir.",
    nodes: [
      { title: "Arayüz · Terminal", text: "Tek komut, iki yüzey" },
      { title: "Komut", text: "Idempotency anahtarıyla" },
      { title: "Aggregate", text: "Durum makinesi kuralları" },
      { title: "Olay deposu", text: "Yalnız ekleme" },
      { title: "Okuma modeli", text: "Arama ve raporlar" },
    ],
    outbox: "Outbox → Redpanda → partner havayolları (ETSU)",
    events: ["TicketIssued", "CouponCheckedIn", "CouponLifted", "CouponFlown", "CouponsRefunded", "ControlGranted"],
    pillars: [
      { title: "Event sourcing", text: "Her değişiklik değişmez bir olay. Denetim kaydı sistemin kendisi." },
      { title: "CQRS", text: "Komutlar olaylardan, arama ve raporlar okuma modelinden." },
      { title: "Açık durum makinesi", text: "17 statü, tanımlı geçişler. İzin verilmeyen geçiş reddedilir." },
      { title: "Idempotency", text: "Çift tıklama çift satış üretmez. Aynı işlem, aynı sonuç." },
      { title: "Outbox", text: "Kayıt ve mesaj yayını aynı işlemde. Olay kaybolmaz." },
      { title: "Hexagonal", text: "Domain çerçeve bilmez. Fiyatlama, DCS ve envanter port arkasında." },
    ],
  },
  cta: {
    title: "Siz hazırsanız, sistem hazır.",
    sub: "Beş rol, dört modül, tek motor. Giriş yapın ve bir bileti kesiminden uçuşuna kadar yönetin.",
    primary: "Sisteme giriş",
    secondary: "Dokümantasyon",
  },
  footer: {
    line: "IATA Ticketing Handbook temelli biletleme platformu.",
    note: "Bu bir tanıtım prototipidir; veriler örnektir.",
    top: "Başa dön",
  },
};

export type LandingCopy = typeof tr;

const en: LandingCopy = {
  nav: {
    product: "Product",
    modules: "Modules",
    lifecycle: "Lifecycle",
    architecture: "Architecture",
    login: "Sign in",
  },
  hero: {
    badge: "Built on the IATA Ticketing Handbook",
    badgeCta: "Live demo",
    title1: "Ticketing,",
    title2: "reimagined.",
    sub: "Troya Suite brings the ticketing core of a PSS — from ticket and EMD issuance to exchange, refund and check-in — into one modern interface, governed by IATA rules.",
    primary: "Sign in",
    secondary: "Explore the product",
    trust: ["17 coupon statuses", "15 Handbook chapters", "Türkçe · English"],
    hub: "Istanbul · IST",
    ticketCard: { label: "Electronic ticket", route: "IST → LHR · TK1979" },
    etsuCard: { label: "ETSU · status update", text: "Sent to partners", time: "just now" },
    drag: "Drag to rotate",
    live: "live",
  },
  product: {
    eyebrow: "Product",
    title: "Clarity instead of cryptic screens.",
    sub: "Commands memorised on the terminal become a single click. One command, two surfaces: the terminal and the interface both reach the same engine.",
    url: "troya-suite / tickets / 2351234567890",
    alt: "Troya Suite ticket record: electronic ticket, coupons, validity and actions",
    mapTitle: "One command, two surfaces",
    map: [
      { cmd: "TKTT/2351234567890", ui: "Open ticket" },
      { cmd: "TRF/CPN1/INV", ui: "Refund" },
      { cmd: "ETKT/VOID/235…", ui: "Void" },
      { cmd: "TWD/SCHD", ui: "Schedule change" },
    ],
  },
  standards: {
    label: "Speaks industry standards",
    items: [
      "IATA Ticketing Handbook", "Resolution 850m", "Resolution 1700", "RP 1726", "ATPCO Cat 16 · 31 · 33",
      "EU 261/2004", "SHY-YOLCU", "UK261", "EDIFACT · NDC", "PCI DSS",
    ],
  },
  modules: {
    eyebrow: "Modules",
    title: "One platform. Every desk.",
    sub: "From sales to the counter, from operations to accounting — the same engine, the same rules.",
    tabs: [
      {
        key: "issue", label: "Ticketing", img: "fare", focus: 64,
        title: "The system quotes, the agent chooses.",
        text: "Enter the route and date; the system lists flights and fare families. Booking class, fare basis and the tax breakdown follow on their own.",
        bullets: ["Flight and fare list", "Summary and declaration before issuing", "Group and family issuance, lap infants", "Idempotent issuance against double clicks"],
      },
      {
        key: "servicing", label: "Servicing", img: "ticket", focus: 8,
        title: "Exchange, refund, void — the system does the maths.",
        text: "Penalties, tax refunds and VAT come from the fare rules. Agents never type amounts; they confirm the result and its reasoning.",
        bullets: ["Cat 16 · 31 · 33 penalty layer", "Refundability per tax", "Reissue difference and residual document", "Control transfer and refund-cancel"],
      },
      {
        key: "checkin", label: "Check-in", img: "checkin", focus: 62,
        title: "Seats by aircraft type, acceptance by rule.",
        text: "The seat map is drawn from the real cabin layout. Exit-row, infant and special-passenger rules are enforced on the server too.",
        bullets: ["Five aircraft types, real cabin layouts", "APIS and travel document checks", "Acceptance window, approved late check-in", "Boarding pass, coupon C → L → F"],
      },
      {
        key: "ops", label: "Operations", img: "ops", focus: 20,
        title: "The whole hub, on one screen.",
        text: "A live departures board, alerts ranked by severity and passenger rights. When a flight is delayed, the compensation amount is ready.",
        bullets: ["A-CDM flight states", "No-show, MCT and baggage alerts", "EU261 · SHY-YOLCU · UK261", "Bulk schedule changes"],
      },
      {
        key: "reports", label: "Reporting", img: "financial", focus: 18,
        title: "Accounting derived from the event log.",
        text: "Sales, financial reports and the VAT breakdown are computed from the event log. Period closing produces a signed document and locks the period.",
        bullets: ["Penalty, tax and VAT breakdown", "Period closing and lock", "ADM / ACM memos", "Excel-friendly exports"],
      },
    ],
    pause: "Pause auto-advance",
    play: "Resume auto-advance",
  },
  lifecycle: {
    eyebrow: "Coupon lifecycle",
    title: "Every coupon has a story.",
    sub: "Statuses move through an explicit state machine. Disallowed transitions cannot happen, final statuses close; every transition lands on the timeline.",
    steps: [
      { code: "O", name: "Open", text: "The ticket is issued; the coupon is open for use." },
      { code: "C", name: "Checked in", text: "The passenger is accepted and seated." },
      { code: "L", name: "Lifted", text: "The boarding pass is scanned at the gate." },
      { code: "F", name: "Flown", text: "The flight closes; the coupon moves to settlement." },
    ],
    gridTitle: "The Handbook's 17 statuses, one vocabulary.",
    gridSub: "Colour tells the family, the code tells the identity.",
    interim: "Interim statuses",
    final: "Final statuses",
  },
  capabilities: {
    eyebrow: "Capabilities",
    title: "The whole working day, in one place.",
    sub: "The Handbook's major functions, with their rules: each comes with locked buttons, a stated reason and an audit record.",
    items: [
      { icon: "ticket", title: "Tickets and EMDs", text: "EMD-A and EMD-S, associated or standalone; service codes via RFISC." },
      { icon: "refund", title: "Refund and void", text: "Same-day void, refunds by fare rule, refund-cancel in the same period." },
      { icon: "exchange", title: "Exchange and reissue", text: "Fare difference, tax difference and residual; validity kept by the rules." },
      { icon: "control", title: "Control transfer", text: "One carrier holds coupon control; transfers need a bilateral agreement and expire." },
      { icon: "irrop", title: "IRROP and FIM", text: "Endorsement and FIM reference for airline-initiated changes." },
      { icon: "rights", title: "Passenger rights", text: "Compensation amounts under EU261, SHY-YOLCU and UK261." },
      { icon: "queue", title: "Queues", text: "Ticketing time limits, IRROP and schedule-change work derived from records." },
      { icon: "memo", title: "ADM / ACM", text: "Res. 850m: dispute window, nine-month limit, BSP period." },
      { icon: "roles", title: "Five roles, clear rights", text: "A cumulative permission matrix; a locked button says why." },
      { icon: "chat", title: "Team messaging", text: "Channels, presence and messages with tickets attached." },
      { icon: "palette", title: "⌘K command palette", text: "Ticket, EMD, PNR or order — one key, one number." },
      { icon: "lang", title: "Turkish and English", text: "Interface, error messages and documents in both languages." },
    ],
  },
  stats: [
    { value: "17", label: "official coupon statuses" },
    { value: "15", label: "Handbook chapters" },
    { value: "37", label: "screens" },
    { value: "600+", label: "automated tests" },
  ],
  architecture: {
    eyebrow: "Architecture",
    title: "The record is the domain.",
    sub: "State is derived from events; nothing is overwritten. Every refund, every void, every control transfer can be read back later.",
    nodes: [
      { title: "Interface · Terminal", text: "One command, two surfaces" },
      { title: "Command", text: "With an idempotency key" },
      { title: "Aggregate", text: "State machine rules" },
      { title: "Event store", text: "Append-only" },
      { title: "Read model", text: "Search and reports" },
    ],
    outbox: "Outbox → Redpanda → partner airlines (ETSU)",
    events: ["TicketIssued", "CouponCheckedIn", "CouponLifted", "CouponFlown", "CouponsRefunded", "ControlGranted"],
    pillars: [
      { title: "Event sourcing", text: "Every change is an immutable event. The audit trail is the system itself." },
      { title: "CQRS", text: "Commands from events; search and reports from the read model." },
      { title: "Explicit state machine", text: "17 statuses, defined transitions. Disallowed ones are rejected." },
      { title: "Idempotency", text: "A double click never sells twice. Same request, same result." },
      { title: "Outbox", text: "The record and the message are published in one transaction." },
      { title: "Hexagonal", text: "The domain knows no framework. Pricing, DCS and inventory sit behind ports." },
    ],
  },
  cta: {
    title: "If you're ready, the system is.",
    sub: "Five roles, four modules, one engine. Sign in and take a ticket from issuance to flown.",
    primary: "Sign in",
    secondary: "Documentation",
  },
  footer: {
    line: "A ticketing platform built on the IATA Ticketing Handbook.",
    note: "This is a demo prototype; all data is sample data.",
    top: "Back to top",
  },
};

export const COPY = { tr, en } as const;
